import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Chart from "../components/Chart";

export default function Home() {
  const [value, setValue] = useState("");

  //Specify your filter here
  let filter =
    value == ""
      ? {}
      : {
          "shipping-source.country": value,
        };

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>UPS Analytics Dashboard</h1>
        {/* <iframe
          width="1000"
          height="600"
          src="https://charts.mongodb.com/charts-eugene-wbjar/embed/dashboards?id=ed21e9b8-d95c-49dc-a179-699fbf8cc7b5&theme=light&autoRefresh=true&maxDataAge=3600&showTitleAndDesc=true&scalingWidth=scale&scalingHeight=scale"
        ></iframe> */}
        <Chart
          height={"600px"}
          width={"800px"}
          //filter={filter}
          filter={filter}
          chartId={"624c1cab-b920-4b80-8a3f-716b757c44ba"}
        />
        <p className={styles.description}>
          <select
            value={value}
            onChange={(e) => {
              setValue(e.target.value);
            }}
          >
            <option value="">All countries</option>
            <option value="GB">United Kingdom</option>
            <option value="US">United States</option>
            <option value="SG">Singapore</option>
          </select>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.mongodb.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/mongodb.png"
              alt="MongoDB Logo"
              width={72}
              height={19}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
